### ISSUE TITLE
Can't create bin

### ISSUE THREAD

**Issue by Ele-M-ent** [Kong/mockbin#103]
Hi,

I've deployed mockbin on a Ubuntu 18.04 server and I only updated the package.json file to edit the 'redis' part.

When I launch the node app with 'npm start' everything looks fine, I can access to the app with my browser, but when I go to 'Create Bin' page and click on 'Create Bin' button, I have, during 1/2 seconds, a page that indicate a Redirection but I stay on the 'Create Bin' page and I can see this in the URL : http://mydomain:8080/bin/create#{res._headers.location}/view

What did I do wrong ?

Thanks guys

**Comment by nicolasmoreira** [comment]
Here is the fix (src/views/redirect.pug):

`
doctype html
html
  head
    meta(http-equiv='refresh', content='0; url=' + res._headers.location + '/view')

  body
    p Redirecting to 
      a(href=res._headers.location + '/view') #{res._headers.location}/view
`
