### ISSUE TITLE
Bins not working anymore

### ISSUE THREAD

**Issue by mroloux** [Kong/mockbin#110]
Hi,

Since yesterday I noticed that none of my bins are working. The sample bins seem to be down as well (e.g. https://mockbin.org/bin/bbe7f656-12d6-4877-9fa8-5cd61f9522a9/view).

Is this a known issue?

Thanks

**Comment by twiggy** [comment]
Having the same issue, but I don't know when my mock was last working.

**Comment by jackkav** [comment]
mockbin functionality will be moved into insomnia in an upcoming release
