### ISSUE TITLE
Allow editing of bins

### ISSUE THREAD

**Issue by ghost** [Kong/mockbin#14]
Maybe I didn't see the button, but it doesn't seem possible to edit a bin once created. I can see the arguments for/against this one - mainly that it adds complexity.

**Comment by ahmadnassri** [comment]
no edits for now, feature coming soon.

**Comment by jthomas** [comment]
+1 on this.

**Comment by ahmadnassri** [comment]
working on this for our next release!

**Comment by mitar** [comment]
+1 (editing or forking/cloning)

**Comment by granchi** [comment]
+1

**Comment by Shawn-Cao** [comment]
+1
Mockbin is very promising for API contract testing. And allowing edit enables we to change response without change fixture.

**Comment by m4ss1m0g** [comment]
+1

**Comment by jackkav** [comment]
done
