### ISSUE TITLE
Cannot create new APIs.

### ISSUE THREAD

**Issue by amal-v** [Kong/mockbin#48]
After basic installation with docker in local machine. The Mockbin application is launched in port 8080 but while creating new APIs its giving a timeout.

> starting server on port: 8080
> GET / 304 301.043 ms - -
> GET /bin/create 200 76.276 ms - -
> POST /bin/create 201 15.404 ms - 269
> GET /bin/1c4a8e63-2327-4597-826e-137cbd2ccba5/view - - ms - -
> GET /bin/d0cfaf36-8e9c-48d5-be9b-a199c1160e70/view - - ms - -
> GET /bin/0525b904-371c-4b9d-acd0-648e815ca902/view - - ms - -

These are the commands that were used to run the application.
`sudo docker run -d -p 6379:6379 --name mockbin_redis redis`
`sudo docker run -d -p 8080:8080 --link mockbin_redis:redis mashape/mockbin`

There are no logs listed in the docker logs.

**Comment by ahmadnassri** [comment]
thanks for reporting, will make a note to add proper docker logs as well.

**Comment by AmalQB** [comment]
@ahmadnassri Can you help me find the root cause of this issue. 
Is there some location inside of docker where I can look for mockbin logs?.

**Comment by hiredgun** [comment]
Came across the same issue. I can create bin successfully but when I try to make a request with generated bin id in Postman then I get a timeout.

**Comment by marceldiass** [comment]
I think this PR https://github.com/Mashape/mockbin/pull/57 fix the problem.

**Comment by ahmadnassri** [comment]
great, about to push new release with that fix
