### ISSUE TITLE
MockBin not working correctly created via Create Bin

### ISSUE THREAD

**Issue by DeonKuhn** [Kong/mockbin#66]
https://mockbin.org/bin/212e66e5-ff57-47a3-8e65-fb825534b42a/view

**Comment by BEllis** [comment]
I'm having the same problem. I've tried mockbin.com and mockbin.org and created several bins.

http://www.mockbin.com/bin/2686b163-e8da-4889-a0ec-c3b51bd4744a

**Comment by BEllis** [comment]
It gives the same view with view / detail / no extension.

log never appears to show any requests despite me calling the bin URL several times.

**Comment by fishjimi** [comment]
I guess the redis server has down, I am now using MockBin on my local server

**Comment by tutnes** [comment]
I am having the same issue, and I see that the mobckbin build has failed recently. Could this be the issue?

**Comment by mattvaldez** [comment]
Also experiencing this issue.
[http://mockbin.org/bin/6d772ebe-25d1-4025-897a-a9817f6213c8/view](http://mockbin.org/bin/6d772ebe-25d1-4025-897a-a9817f6213c8/view)

**Comment by fishjimi** [comment]
Just now , it worked again ....@DeonKuhn @BEllis @tutnes @mattvaldez @

**Comment by abbi-gaurav** [comment]
Same problem for me also. Still not working

**Comment by emrahcetiner** [comment]
Still not working

**Comment by lucasmaiasilva** [comment]
Why guys? Mockbin was great...

**Comment by kurtulussahin** [comment]
until the problem is resolved:
https://requestloggerbin.herokuapp.com/

**Comment by lucapalano** [comment]
To date, still not working

**Comment by Pammix86** [comment]
Still not working

**Comment by foinf** [comment]
Can confirm. Not working.

> until the problem is resolved:
> https://requestloggerbin.herokuapp.com/

This works! Thanks!

**Comment by nijikokun** [comment]
See #78
