### ISSUE TITLE
Mock Bin is not working correctly on Mockbin.org via create

### ISSUE THREAD

**Issue by dcghost82** [Kong/mockbin#68]
Issue similar to https://github.com/Mashape/mockbin/issues/49

Ex: http://mockbin.org/bin/33c3fcf1-b6be-472d-b715-6a6ba69b76e4/view

Ex: http://mockbin.org/bin/ef4ac8ce-4d8a-4adf-93bf-13fb4d26c984/log

**Comment by jimbitol** [comment]
not working

**Comment by dcghost82** [comment]
Not sure if that was meant to say, now working, but I just checked and I still don't see the correct layout. I've kept the formatting of my REST resource to you and have created new BINs, but nothing shows up. I used to be able to click around where I needed, now I have to manually change the URL in order to get to the log screen and when I do nothing is showing up.
😞
________________________________

**Comment by kurtulussahin** [comment]
until the problem is resolved:
https://requestloggerbin.herokuapp.com/

**Comment by warmfire540** [comment]
> until the problem is resolved:
> https://requestloggerbin.herokuapp.com/

what is the retention period on these logs - anyway to delete a bin after testing?

**Comment by nijikokun** [comment]
See #78
