### ISSUE TITLE
Mockbin is no longer creating bins

### ISSUE THREAD

**Issue by carolalertsense** [Kong/mockbin#69]
http://mockbin.org/bin/bd3cf02b-82ad-4ced-8408-cc4bc8fecad5/view

**Comment by carolalertsense** [comment]
It looks like issue #66 has regressed.

**Comment by jimbitol** [comment]
+1

**Comment by nguilford** [comment]
I can reproduce this as well. Is this likely to be fixed?

**Comment by dougboykin** [comment]
I am not able to see the data POSTed to my bin.

**Comment by basilmariano** [comment]
I cant see logs on my bin also. 
However it works on my old bin.  [This is my old bin I created before](http://mockbin.org/bin/8f7cca29-31aa-41af-87d2-931c0e006205/log) But it looks like it only show the First 13 logs.

if i create another bin now, it will only show http://mockbin.org/bin/99aef1dd-5376-43d6-8604-7e280b81fec4/view

**Comment by kurtulussahin** [comment]
+1

**Comment by olivier5741** [comment]
+1

**Comment by kurtulussahin** [comment]
https://requestloggerbin.herokuapp.com/

until the problem is resolved

**Comment by steve-white** [comment]
+1

**Comment by kurtulussahin** [comment]
mockbin.org's redis memory  limit is full. 
you can set "maxmemory-policy" as "allkeys-lru"

**Comment by nijikokun** [comment]
See #78
