### ISSUE TITLE
mockbin.org is no longer creating bins because of redis memory

### ISSUE THREAD

**Issue by kurtulussahin** [Kong/mockbin#78]
mock Bin is not working correctly on Mockbin.org via create bins.
Because mockbin.org's redis memory limit is full, or redis is down.
you can set "maxmemory-policy" as "allkeys-lru".
please.

until the problem is resolved:
https://requestloggerbin.herokuapp.com/

**Comment by acrodrig** [comment]
Is this going to be solved?

**Comment by judavi** [comment]
:/ looks like is still not working properly

**Comment by ianrtracey** [comment]
Looks like this is still broken :(

**Comment by Marusyk** [comment]
any news?

**Comment by z3ntu** [comment]
I was already wondering why mockbin.org wasn't returning anything for me.
Thanks @kurtulussahin for the hosted version, it was really useful for me!

**Comment by nhmaha** [comment]
+1

**Comment by chb0github** [comment]
Considering how old some of these PRs are and how old (and unaddressed) some of the issues are I am suspecting a fork is in order.

**Comment by lastgleam** [comment]
still broken now👎 

thanks @kurtulussahin !

**Comment by Drjacky** [comment]
Still not working.

**Comment by nijikokun** [comment]
Sorry for the delay on this ❤️ 

I've gone ahead and updated the eviction policy to be `allkeys-lru`.

Closing as there has been an action taken, should this still occur, let's re-open at that time and find alternative means of addressing the issue. 🤗
