### ISSUE TITLE
Infinite loading on bin creation

### ISSUE THREAD

**Issue by lucas093** [Kong/mockbin#79]
Hi,

When I use mockbin on my server, create a bin with this url '/bin/create'
I can see a blank page with this message :
```
Redirecting to /bin/1cc115ab-8651-4359-b868-1b24e69c9c3c/view
```
But it can't reach this link ... 

on the server side I can read : 
```
starting server on port: 8080
GET /bin/create 200 2300.757 ms - -
POST /bin/create 201 161.746 ms - 269
```
What's the problem ???

**Comment by yayoc** [comment]
@lucas093 
I think you have to run `redis` on your server.
